version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        restart: unless-stopped
        build:
            context: ./php/src
            dockerfile: php-apache
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 80:80
    db:
        container_name: mysql-database
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: tmppass
            MYSQL_DATABASE: sitedb
            MYSQL_USER: mysqladmin
            MYSQL_PASSWORD: mysqladmin
        ports:
            - "3306:3306"
